# -*- coding: utf-8 -*-
"""Exercise1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hg5leRGcfVLrTkIC4trLG1j4sPQZrSZx

# **Exercise 1**

Implement diffierent types of agent implementation to do a certain task of your choice.
1. Table Driven Agent
2. Simple Reflex Agent

<p><b>Before implementation describe the following:</b></p>

1. Agent Description: The aim of the agent .....
2. List the sensors:
3. Sensors' values:
3. List the actions:
4. Agent function: perception --> action
"""

# Table Driven Agent

table = {
    ('A', 'Dirty'): 'Suck',
    ('A', 'Clean'): 'Right',
    ('B', 'Dirty'): 'Suck',
    ('B', 'Clean'): 'Left'
}

percepts = []

def lookup(percept, table):
    return table.get(percept)

def table_driven_agent(percept):
    print("Perception:", percept)
    percepts.append(percept)
    action = lookup(percept, table)
    return action

# Simple Reflex Agent

def simple_reflex_agent(percept):
    location = percept[0]
    status = percept[1]

    if status == 'Dirty':
        return 'Suck'
    elif location == 'A':
        return 'Right'
    elif location == 'B':
        return 'Left'

import random

Location = random.choice(['A', 'B'])
Condition = random.choice(['Clean', 'Dirty'])

while True:
    print("\nCurrent Location:", Location)
    print("Current Condition:", Condition)

    # Choose one agent
    action = simple_reflex_agent((Location, Condition))
    # action = table_driven_agent((Location, Condition))

    print("Action:", action)

    cmd = input("Continue? (yes/no): ")
    if cmd == 'no':
        break

    if action == 'Right':
        Location = 'B'
        Condition = random.choice(['Clean', 'Dirty'])
    elif action == 'Left':
        Location = 'A'
        Condition = random.choice(['Clean', 'Dirty'])
    else:
        Condition = 'Clean'