# -*- coding: utf-8 -*-
"""search(BFS,DFS).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DhhtzdDBU7uYWPMyJrR89AUDDtBvnumk
"""

romanian_map = {
    'Arad': {'Sibiu':140, 'Zerind':75, 'Timisoara':118},
    'Zerind': {'Arad':75, 'Oradea':71},
    'Oradea': {'Zerind':71, 'Sibiu': 151},
    'Sibiu': {'Arad':140, 'Oradea':151, 'Fagaras':99, 'Rimnicu':80},
    'Timisoara': {'Arad': 118, 'Lugoj':111},
    'Lugoj': {'Timisoara':111, 'Mehadia':70},
    'Mehadia': {'Lugoj': 70, 'Drobeta':75},
    'Drobeta': {'Mehadia':75, 'Craiova':120},
    'Craiova': {'Drobeta': 120, 'Rimnicu': 146, 'Pitesti': 138},
    'Rimnicu': {'Sibiu': 80, 'Craiova': 146, 'Pitesti': 97},
    'Fagaras': {'Sibiu':99, 'Bucharest':211},
    'Pitesti': {'Rimnicu': 97, 'Craiova':138, 'Bucharest':101},
    'Bucharest': {'Fagaras':211, 'Pitesti': 101, 'Giurgiu':90, 'Urziceni':85},
    'Giurgiu': {'Bucharest': 90},
    'Urziceni': {'Bucharest': 85, 'Vaslui':142, 'Hirsova':98},
    'Hirsova': {'Urziceni':98, 'Eforie':86},
    'Eforie': {'Hirsova':86},
    'Vaslui': {'Iasi': 92, 'Urziceni':142},
    'Iasi': {'Vaslui':92, 'Neamt': 87},
    'Neamt': {'Iasi':87}
}

romanian_map['Arad']

{'Sibiu': 140, 'Timisoara': 118, 'Zerind': 75}


list(romanian_map['Arad'].keys())

['Sibiu', 'Zerind', 'Timisoara']


romanian_map['Arad']['Zerind']

list(romanian_map.keys())

['Arad',
		 'Zerind',
		 'Oradea',
		 'Sibiu',
		 'Timisoara',
		 'Lugoj',
		 'Mehadia',
		 'Drobeta',
		 'Craiova',
		 'Rimnicu',
		 'Fagaras',
		 'Pitesti',
		 'Bucharest',
		 'Giurgiu',
		 'Urziceni',
		 'Hirsova',
		 'Eforie',
		 'Vaslui',
		 'Iasi',
		 'Neamt']

def bfs(startingNode, destinationNode, G):
    reached = [] # to store reached (generated) nodes
    expand_sequence = [] # to store the order of nodes expanded
    frontier = []

    snode = {'City':startingNode,'Path cost':0, 'Path':[startingNode]}
    frontier.append(snode)    # insert the starting node
    reached.append(startingNode)

    while len(frontier) > 0:
        print(frontier)
        unode  = frontier.pop(0)     # selceting the node to expand
        u = unode['City']
        expand_sequence.append(u)
        print(u + " expanding..")
        # expand u

        for v in G[u].keys():
            if v not in reached: # process if v is not reached (generated) yet
                print(v+" generated.")
                cost = unode['Path cost'] + G[u][v]
                path =  unode['Path']+ [v]
                vnode = {'City': v,'Path cost': cost,'Path': path}
                frontier.append(vnode)# store the new child node in the frontier
                reached.append(v)
                # goal test
                if v == destinationNode:
                    #print(vnode)
                    print(expand_sequence)
                    return vnode # breaking from while
    print('Failed')

bfs('Arad', 'Bucharest', romanian_map) # change the soure and destination


[{'City': 'Arad', 'Path cost': 0, 'Path': ['Arad']}]


[{'City': 'Sibiu', 'Path cost': 140, 'Path': ['Arad', 'Sibiu']}, {'City': 'Zerind', 'Path cost': 75, 'Path': ['Arad', 'Zerind']}, {'City': 'Timisoara', 'Path cost': 118, 'Path': ['Arad', 'Timisoara']}]

[{'City': 'Zerind', 'Path cost': 75, 'Path': ['Arad', 'Zerind']}, {'City': 'Timisoara', 'Path cost': 118, 'Path': ['Arad', 'Timisoara']}, {'City': 'Oradea', 'Path cost': 291, 'Path': ['Arad', 'Sibiu', 'Oradea']}, {'City': 'Fagaras', 'Path cost': 239, 'Path': ['Arad', 'Sibiu', 'Fagaras']}, {'City': 'Rimnicu', 'Path cost': 220, 'Path': ['Arad', 'Sibiu', 'Rimnicu']}]

[{'City': 'Timisoara', 'Path cost': 118, 'Path': ['Arad', 'Timisoara']}, {'City': 'Oradea', 'Path cost': 291, 'Path': ['Arad', 'Sibiu', 'Oradea']}, {'City': 'Fagaras', 'Path cost': 239, 'Path': ['Arad', 'Sibiu', 'Fagaras']}, {'City': 'Rimnicu', 'Path cost': 220, 'Path': ['Arad', 'Sibiu', 'Rimnicu']}]
[{'City': 'Oradea', 'Path cost': 291, 'Path': ['Arad', 'Sibiu', 'Oradea']}, {'City': 'Fagaras', 'Path cost': 239, 'Path': ['Arad', 'Sibiu', 'Fagaras']}, {'City': 'Rimnicu', 'Path cost': 220, 'Path': ['Arad', 'Sibiu', 'Rimnicu']}, {'City': 'Lugoj', 'Path cost': 229, 'Path': ['Arad', 'Timisoara', 'Lugoj']}]

[{'City': 'Fagaras', 'Path cost': 239, 'Path': ['Arad', 'Sibiu', 'Fagaras']}, {'City': 'Rimnicu', 'Path cost': 220, 'Path': ['Arad', 'Sibiu', 'Rimnicu']}, {'City': 'Lugoj', 'Path cost': 229, 'Path': ['Arad', 'Timisoara', 'Lugoj']}]

['Arad', 'Sibiu', 'Zerind', 'Timisoara', 'Oradea', 'Fagaras']

{'City': 'Bucharest',
		 'Path': ['Arad', 'Sibiu', 'Fagaras', 'Bucharest'],
		 'Path cost': 450}

"""DFS"""

romanian_map = {
    'Arad': {'Sibiu':140, 'Zerind':75, 'Timisoara':118},
    'Zerind': {'Arad':75, 'Oradea':71},
    'Oradea': {'Zerind':71, 'Sibiu': 151},
    'Sibiu': {'Arad':140, 'Oradea':151, 'Fagaras':99, 'Rimnicu':80},
    'Timisoara': {'Arad': 118, 'Lugoj':111},
    'Lugoj': {'Timisoara':111, 'Mehadia':70},
    'Mehadia': {'Lugoj': 70, 'Drobeta':75},
    'Drobeta': {'Mehadia':75, 'Craiova':120},
    'Craiova': {'Drobeta': 120, 'Rimnicu': 146, 'Pitesti': 138},
    'Rimnicu': {'Sibiu': 80, 'Craiova': 146, 'Pitesti': 97},
    'Fagaras': {'Sibiu':99, 'Bucharest':211},
    'Pitesti': {'Rimnicu': 97, 'Craiova':138, 'Bucharest':101},
    'Bucharest': {'Fagaras':211, 'Pitesti': 101, 'Giurgiu':90, 'Urziceni':85},
    'Giurgiu': {'Bucharest': 90},
    'Urziceni': {'Bucharest': 85, 'Vaslui':142, 'Hirsova':98},
    'Hirsova': {'Urziceni':98, 'Eforie':86},
    'Eforie': {'Hirsova':86},
    'Vaslui': {'Iasi': 92, 'Urziceni':142},
    'Iasi': {'Vaslui':92, 'Neamt': 87},
    'Neamt': {'Iasi':87}
}

romanian_map['Arad']

{'Sibiu': 140, 'Timisoara': 118, 'Zerind': 75}


list(romanian_map['Arad'].keys())

['Sibiu', 'Zerind', 'Timisoara']


romanian_map['Arad']['Zerind']

list(romanian_map.keys())

['Arad',
		 'Zerind',
		 'Oradea',
		 'Sibiu',
		 'Timisoara',
		 'Lugoj',
		 'Mehadia',
		 'Drobeta',
		 'Craiova',
		 'Rimnicu',
		 'Fagaras',
		 'Pitesti',
		 'Bucharest',
		 'Giurgiu',
		 'Urziceni',
		 'Hirsova',
		 'Eforie',
		 'Vaslui',
		 'Iasi',
		 'Neamt']

# DFS using Stack (List)
def dfs(startingNode, destinationNode, G):
    reached = []
    expand_sequence = []
    stack = []

    snode = {'City': startingNode, 'Path cost': 0, 'Path': [startingNode]}
    stack.append(snode)
    reached.append(startingNode)

    while len(stack) > 0:
        print("Stack:", stack)

        unode = stack.pop()   # LIFO
        u = unode['City']
        expand_sequence.append(u)
        print(u, "expanding..")

        if u == destinationNode:
            print("Expand sequence:", expand_sequence)
            print("Path:", unode['Path'])
            print("Total Cost:", unode['Path cost'])
            return unode

        for v in G[u].keys():
            if v not in reached:
                print(v, "generated.")
                cost = unode['Path cost'] + G[u][v]
                path = unode['Path'] + [v]
                vnode = {'City': v, 'Path cost': cost, 'Path': path}
                stack.append(vnode)
                reached.append(v)

    print("Failed")

dfs('Arad', 'Bucharest', romanian_map) # change the soure and destination


[{'City': 'Arad', 'Path cost': 0, 'Path': ['Arad']}]


[{'City': 'Sibiu', 'Path cost': 140, 'Path': ['Arad', 'Sibiu']}, {'City': 'Zerind', 'Path cost': 75, 'Path': ['Arad', 'Zerind']}, {'City': 'Timisoara', 'Path cost': 118, 'Path': ['Arad', 'Timisoara']}]

[{'City': 'Zerind', 'Path cost': 75, 'Path': ['Arad', 'Zerind']}, {'City': 'Timisoara', 'Path cost': 118, 'Path': ['Arad', 'Timisoara']}, {'City': 'Oradea', 'Path cost': 291, 'Path': ['Arad', 'Sibiu', 'Oradea']}, {'City': 'Fagaras', 'Path cost': 239, 'Path': ['Arad', 'Sibiu', 'Fagaras']}, {'City': 'Rimnicu', 'Path cost': 220, 'Path': ['Arad', 'Sibiu', 'Rimnicu']}]

[{'City': 'Timisoara', 'Path cost': 118, 'Path': ['Arad', 'Timisoara']}, {'City': 'Oradea', 'Path cost': 291, 'Path': ['Arad', 'Sibiu', 'Oradea']}, {'City': 'Fagaras', 'Path cost': 239, 'Path': ['Arad', 'Sibiu', 'Fagaras']}, {'City': 'Rimnicu', 'Path cost': 220, 'Path': ['Arad', 'Sibiu', 'Rimnicu']}]
[{'City': 'Oradea', 'Path cost': 291, 'Path': ['Arad', 'Sibiu', 'Oradea']}, {'City': 'Fagaras', 'Path cost': 239, 'Path': ['Arad', 'Sibiu', 'Fagaras']}, {'City': 'Rimnicu', 'Path cost': 220, 'Path': ['Arad', 'Sibiu', 'Rimnicu']}, {'City': 'Lugoj', 'Path cost': 229, 'Path': ['Arad', 'Timisoara', 'Lugoj']}]

[{'City': 'Fagaras', 'Path cost': 239, 'Path': ['Arad', 'Sibiu', 'Fagaras']}, {'City': 'Rimnicu', 'Path cost': 220, 'Path': ['Arad', 'Sibiu', 'Rimnicu']}, {'City': 'Lugoj', 'Path cost': 229, 'Path': ['Arad', 'Timisoara', 'Lugoj']}]

['Arad', 'Sibiu', 'Zerind', 'Timisoara', 'Oradea', 'Fagaras']